### PR TITLE
Stop adding NODE_LABEL to build job parameters

### PR DESCRIPTION
**Pull request by andrew-m-leonard**
Fixes: https://github.com/adoptium/infrastructure/issues/2774#issuecomment-1494192694

### CODE REVIEW

**Review by sxa — CHANGES_REQUESTED** [review]
Please change title of the change to `NODE_LABEL` (i.e. remove the extra `L`

**Comment by karianna** [comment]
> Please change title of the commit to `NODE_LABEL` (i.e. remove the extra `L`

Changed it (FYI - you also have that power in the UI going forwards)

**Review by karianna — APPROVED** [review]

**Review by sxa — APPROVED** [review]

**Comment by andrew-m-leonard** [comment]
I reckon, this IS needed to schedule the build jobs, suspect we should be defining the job template with NODE_LABEL instead

**Comment by andrew-m-leonard** [comment]
Close in favour of new PR https://github.com/adoptium/jenkins-helper/pull/55

**Pull request closed without merging**
